<Project>
  <PropertyGroup>
    <Version>1.0.0-preview.1</Version>
    <AssemblyVersion>1.0.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Company>open-fluent by lepo.co</Company>
    <Authors>open-fluent by lepo.co</Authors>
    <Product>Fluent UI Framework</Product>
    <CommonTags>lepo;lepoco;fluent;framework;pomian;pomianowski</CommonTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <Copyright>(c) open-fluent | Leszek Pomianowski and Contributors. All rights reserved.</Copyright>
    <PackageProjectUrl>https://github.com/open-fluent/ui</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/open-fluent/ui/releases</PackageReleaseNotes>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageIconUrl>https://github.com/open-fluent/ui/main/build/nuget.png</PackageIconUrl>
  </PropertyGroup>

  <PropertyGroup>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>true</WarningsAsErrors>
    <NoWarn>$(NoWarn);CS8500</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <RepositoryDirectory>$(MSBuildThisFileDirectory)</RepositoryDirectory>
    <BuildToolsDirectory>$(RepositoryDirectory)build\</BuildToolsDirectory>
  </PropertyGroup>

  <PropertyGroup>
    <IsTestProject>$(MSBuildProjectName.Contains('Test'))</IsTestProject>
    <IsCoreProject Condition="$(IsTestProject)">False</IsCoreProject>
    <IsCoreProject Condition="'$(IsCoreProject)' == ''">True</IsCoreProject>
    <IsBelowNet8
      Condition="'$(TargetFramework)' == 'netstandard2.0'
                 Or '$(TargetFramework)' == 'netstandard2.1'
                 Or '$(TargetFramework)' == 'net462'
                 Or '$(TargetFramework)' == 'net472'
                 Or '$(TargetFramework)' == 'net481'
                 Or '$(TargetFramework)' == 'net5.0'
                 Or '$(TargetFramework)' == 'net6.0'
                 Or '$(TargetFramework)' == 'net7.0'
                 Or '$(TargetFramework)' == 'net8.0'
                 Or '$(TargetFramework)' == 'net9.0'
                 Or '$(TargetFramework)' == 'net10.0'"
      >True</IsBelowNet8
    >
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <IsPublishable>true</IsPublishable>
    <ContinuousIntegrationBuild>$(TF_BUILD)</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsBelowNet8)' == 'false'">
    <DefineConstants>$(DefineConstants);NET8_0_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <Choose>
    <When Condition="$(IsCoreProject)">
      <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsPublishable>false</IsPublishable>
        <NoWarn>$(NoWarn);CS8002;SA0001</NoWarn>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <Choose>
    <When Condition="'$(SourceLinkEnabled)' != 'false'">
      <PropertyGroup>
        <!-- Declare that the Repository URL can be published to NuSpec -->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <!-- Embed source files that are not tracked by the source control manager to the PDB -->
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <!-- Include PDB in the built .nupkg -->
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
      </ItemGroup>
    </When>
  </Choose>
</Project>
