<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditLevel>moderate</NuGetAuditLevel>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AsyncFixer" Version="1.6.0" />
    <PackageVersion Include="AwesomeAssertions" Version="9.3.0" />
    <PackageVersion Include="ErrorProne.NET.CoreAnalyzers" Version="0.8.2-beta.1" />
    <PackageVersion Include="ErrorProne.NET.Structs" Version="0.6.1-beta.1" />
    <PackageVersion Include="IDisposableAnalyzers" Version="4.0.8" />
    <PackageVersion Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="1.1.1" />
    <PackageVersion Include="PolySharp" Version="1.15.0" />
    <PackageVersion Include="SharpSource" Version="1.27.1" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <PackageVersion Include="System.Net.Http" Version="4.3.4" />
    <PackageVersion Include="System.Text.Json" Version="10.0.1" />
    <PackageVersion Include="xunit.v3" Version="3.2.1" />
  </ItemGroup>
</Project>
